"""empty message

Revision ID: 411ee8158e29
Revises: 779cbacdf081
Create Date: 2016-10-21 04:18:24.210241

"""

# revision identifiers, used by Alembic.
revision = '411ee8158e29'
down_revision = '779cbacdf081'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input', sa.Column('first_name', sa.String(length=120), nullable=True))
    op.add_column('input', sa.Column('last_name', sa.String(length=120), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('input', 'last_name')
    op.drop_column('input', 'first_name')
    ### end Alembic commands ###
