"""version 2 upgrade hello Adam!

Revision ID: dc590ff3a4f7
Revises: 779cbacdf081
Create Date: 2016-10-21 03:05:04.700902

"""

# revision identifiers, used by Alembic.
revision = 'dc590ff3a4f7'
down_revision = '779cbacdf081'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input', sa.Column('first_name', sa.String(length=120), nullable=True))
    op.add_column('input', sa.Column('last_name', sa.String(length=120), nullable=True))
    # op.drop_column('input', 'person_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('input', sa.Column('person_name', sa.VARCHAR(length=120), nullable=True))
    op.drop_column('input', 'last_name')
    op.drop_column('input', 'first_name')
    ### end Alembic commands ###
